remote_theme: jekyll/minima

keep_files:
  - pagefind

exclude:
  - .obsidian

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-default-layout
  - jekyll-titles-from-headings
title: CS Notes
description: Anubrat Bora
markdown: kramdown
kramdown:
  math_engine: null
