remote_theme: jekyll/minima

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
plugins:
  - jekyll-remote-theme
  - jekyll-feed
title: CS Notes
description: Anubrat Bora
markdown: kramdown
kramdown:
  math_engine: null
